---
# tasks file for docker.ubuntu
- name: Fail if not a supported release of Ubuntu
  fail:
    msg: "{{ ansible_distribution_version }} is not an acceptable version of Ubuntu for this role"
  when: ansible_lsb.id|lower == "ubuntu" and ansible_distribution_version is version_compare('18.04', '<')

- name: Ensure dirmngr is available
  apt:
    pkg: "{{ apt_dirmngr_pkg }}"
    state: present
    update_cache: yes
    cache_valid_time: "{{ docker_apt_cache_valid_time }}"

- name: Add Docker repository key
  apt_key:
    id: "{{ apt_key_sig }}"
    keyserver: "{{ apt_key_url }}"
    state: present
  register: add_repository_key
  ignore_errors: true

- name: Alternative | Add Docker repository key
  shell: "apt-key adv --fetch-keys {{ apt_key_url }}"
  when: add_repository_key is failed

- name: HTTPS APT transport for Docker repository
  apt:
    name: apt-transport-https
    state: present

- name: Add Docker repository and update apt cache
  apt_repository:
    repo: "{{ apt_repository }}"
    mode: '644'
    update_cache: yes
    state: present

- name: Install (or update) docker package
  apt:
    name: "{{ docker_pkg_names }}"
    state: "{{ 'latest' if update_docker_package else 'present' }}"
    update_cache: "{{ update_docker_package }}"
    cache_valid_time: "{{ docker_apt_cache_valid_time }}"

- name: Set systemd playbook var
  set_fact:
    is_systemd: true
  tags: always

# https://github.com/moby/moby/issues/25471#issuecomment-263101090
- name: Creates override directory (systemd)
  file:
    path: /etc/systemd/system/docker.service.d
    state: "{{ (daemon_json is not none) | ternary('directory', 'absent') }}"
    owner: root
    group: root
    mode: 0755
  when:
    - is_systemd
  tags: proxy

- name: Set docker daemon override (systemd)
  copy:
    content: |
      [Service]
      ExecStart=
      ExecStart=/usr/bin/dockerd
    dest: /etc/systemd/system/docker.service.d/override.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - Reload systemd
    - Restart docker
  when: daemon_json is not none and is_systemd

- name: Ensure /etc/docker is present
  file:
    path: /etc/docker
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Set /etc/docker/daemon.json
  copy:
    content: "{{ daemon_json | to_nice_json }}"
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart docker
  when: daemon_json is not none

- name: Check if /etc/updatedb.conf exists
  stat:
    path: /etc/updatedb.conf
  register: updatedb_conf_exists

- name: Ensure updatedb does not index /var/lib/docker
  lineinfile:
    dest: /etc/updatedb.conf
    state: present
    backrefs: yes
    regexp: '^PRUNEPATHS="(/var/lib/docker )?(.*)"$'
    line: 'PRUNEPATHS="/var/lib/docker \2"'
  when: updatedb_conf_exists.stat.exists

- block:
    - name: Check if /etc/default/ufw exists
      stat:
        path: /etc/default/ufw
      register: ufw_default_exists

    - name: Change ufw default forward policy from drop to accept
      lineinfile:
        dest: /etc/default/ufw
        regexp: "^DEFAULT_FORWARD_POLICY="
        line: "DEFAULT_FORWARD_POLICY=\"ACCEPT\""
      when: ufw_default_exists.stat.exists
  when: ufw_set_forward_policy

- name: Start docker
  service:
    name: docker
    state: started
  when: start_docker_daemon

  # ATTENTION: this task can potentially create new users!
- name: Add users to the docker group
  user:
    name:   "{{ item }}"
    groups: docker
    append: yes
  with_items: "{{docker_group_members}}"
  when: docker_group_members is defined

- name: update facts if docker0 is not defined
  setup:
    filter: "ansible_docker0"
  when: ansible_docker0 is not defined
